converter/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.download, name='download'),
]

mp3converter/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('converter.urls', namespace='converter')),
]

converter/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone

class Link(models.Model):
    link_text = models.CharField(max_length=200, default="")
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.link_text

converter/forms.py
from django import forms

from .models import Link

class LinkForm(forms.ModelForm):
    
    class Meta:
        model = Link
        fields = ('link_text',)

    

converter/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .models import Link
from .forms import LinkForm
import youtube_dl
from django.http import HttpResponse
from youtube_dl import YoutubeDL


def index(request):
    latest_link_list = Link.objects.order_by('-pub_date')
    context = {'latest_link_list': latest_link_list}
    return render(request, 'converter/index.html', context)

def download(request):
    if request.method == "POST":
        form = LinkForm(request.POST)
        if form.is_valid():
            link = form.save(commit=False)
            url = link.link_text
            link.save()

            ydl_opts = {'format': 'bestaudio/best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'preferredcodec': 'mp3', 'preferredquality': '192', }], 'quiet': True, 'restrictfilenames': True }

            with YoutubeDL(ydl_opts) as ydl:
                video_info = ydl.extract_info(url, download=False)
                video_url = video_info['url']
                return redirect(video_url)
    else:
        form = LinkForm()
    return render(request, 'converter/link_new.html', {'form': form})

converter/templates/converter/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <title>Simple download mp3 from Youtube</title>
</head>
<body>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <script src="{% static 'js/download.js' %}"></script>

  </body>
</html>

converter/templates/converter/index.html
{% extends 'converter/base.html' %}
{% block content %}
<div class="panel panel-default">
    <h1>Link history</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Link</th>
                <th scope="col">Published</th>
            </tr>
        </thead>
        <tbody>
            {% if latest_link_list %}
                {% for link in latest_link_list %}
                <tr>
                    <td>{{ link.link_text }}</td>
                    <td>{{ link.pub_date }}</td>  
                </tr> 
                {% endfor %}
            {% endif %}
        </tbody>
    </table>
<a href="{% url 'converter:download' %}" class="btn btn-primary">New link</a>
{% endblock content %}
<br><br><br><br>

converter/templates/converter/link_new.html
{% extends 'converter/base.html' %}
{% block content %}
<br>
<form method="POST" class="link-form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock content %}